In [1]:
#Importing Libraries

In [1]:
import numpy as np
import pickle as pkl
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPool2D

from sklearn.neighbors import NearestNeighbors
import os
from numpy.linalg import norm

C:\Users\Sai Siva Teja\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
#Extract Filenames from Folder

In [6]:
filenames = []
for file in os.listdir('dataset/images'):
    filenames.append(os.path.join('dataset/images',file))
    

In [7]:
len(filenames)

44441

In [6]:
#Importing ResNet50 Model and Cofiguration

In [8]:
model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
model.trainable = False

model = tf.keras.models.Sequential([model,
                                   GlobalMaxPool2D()
                                   ])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_max_pooling2d_1 (Glo  (None, 2048)             0         
 balMaxPooling2D)                                                
                                                                 
Total params: 23,587,712
Trainable params: 0
Non-trainable params: 23,587,712
_________________________________________________________________


In [50]:
#Extracting Fetaures from Image

In [9]:
img = image.load_img('dataset/images/1163.jpg', target_size=(224,224))
img_array = image.img_to_array(img)
img_expand_dim = np.expand_dims(img_array, axis=0)
img_preprocess = preprocess_input(img_expand_dim)
result = model.predict(img_preprocess).flatten()
norm_result = result/norm(result)
norm_result

1/1 [==============================] - 1s 1s/step


array([0.00491868, 0.05812981, 0.00543879, ..., 0.00351523, 0.05245367,
       0.03639513], dtype=float32)

In [10]:
def extract_features_from_images(image_path, model):
    img = image.load_img(image_path, target_size=(224,224))
    img_array = image.img_to_array(img)
    img_expand_dim = np.expand_dims(img_array, axis=0)
    img_preprocess = preprocess_input(img_expand_dim)
    result = model.predict(img_preprocess).flatten()
    norm_result = result/norm(result)
    return norm_result

In [11]:
extract_features_from_images(filenames[0], model)

1/1 [==============================] - 0s 95ms/step


array([0.        , 0.01761615, 0.00171596, ..., 0.01247231, 0.02726383,
       0.06899207], dtype=float32)

In [12]:
image_features = []
for file in filenames[0:5]:
    image_features.append(extract_features_from_images(file, model))
image_features

1/1 [==============================] - 0s 111ms/step


[array([0.        , 0.01761615, 0.00171596, ..., 0.01247231, 0.02726383,
        0.06899207], dtype=float32),
 array([0.        , 0.03648941, 0.        , ..., 0.00997929, 0.02375532,
        0.04649908], dtype=float32),
 array([0.        , 0.03642138, 0.00710439, ..., 0.00140777, 0.        ,
        0.05435045], dtype=float32),
 array([0.00232165, 0.05030544, 0.00747743, ..., 0.00346695, 0.03391021,
        0.04565721], dtype=float32),
 array([0.00306837, 0.06240456, 0.        , ..., 0.00170629, 0.02032897,
        0.05833261], dtype=float32)]

In [13]:
Image_features = pkl.dump(image_features, open('Images_features.pkl','wb'))

In [14]:
filenames = pkl.dump(filenames, open('filenames.pkl','wb'))

In [23]:
#Loading Pickle Files

In [15]:
Image_features = pkl.load(open('Images_features.pkl','rb'))

In [16]:
filenames = pkl.load(open('filenames.pkl','rb'))

In [17]:
np.array(Image_features).shape

(5, 2048)